# Hardware configuration for Contabo VPS
# This is a minimal config for CI validation.
# On real deployment, replace with actual hardware-configuration.nix generated by nixos-generate-config

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  # Boot loader configuration
  boot.loader.grub = {
    enable = true;
    device = "/dev/sda"; # Primary disk on most Contabo VPS
    # On actual deployment, verify with: lsblk
  };

  # Root filesystem
  fileSystems."/" = {
    device = "/dev/sda1";
    fsType = "ext4";
  };

  # Swap partition (optional but recommended for VPS)
  swapDevices = [
    { device = "/dev/sda2"; }
  ];

  # Network configuration
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.ens3.useDHCP = lib.mkDefault true; # Common interface name for VPS

  # Hardware optimizations for VPS
  hardware.enableRedistributableFirmware = lib.mkDefault true;
  
  # Kernel modules for virtualized environment
  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # CPU configuration (adjust based on actual VPS specs)
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
